name: Compare results

on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  comparison-compatible-env:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shell: # this may be insufficient because the actual binary of each shell commands may differ...
          - /bin/bash
          - /bin/zsh
          - /bin/ksh
          - /bin/sh
          - /bin/dash
        env_file:
          - env/compatible.env
        overload_file:
          - env/compatible.overload.env
        include:
          - shell: /bin/bash
            function_file_path: export-docker-dotenv
          - shell: /bin/zsh
            function_file_path: export-docker-dotenv
          - shell: /bin/ksh
            function_file_path: export-docker-dotenv
          - shell: /bin/sh
            function_file_path: export-docker-dotenv-without-proc-subst
          - shell: /bin/dash
            function_file_path: export-docker-dotenv-without-proc-subst
    env:
      FUNCTION_FILE_PATH: ${{ matrix.function_file_path }}
    steps:
      - uses: actions/checkout@v3
      - run: ./spec/compare_results.bash '${{ matrix.shell }}' '${{ matrix.env_file }}' '${{ matrix.overload_file }}'
  